# Highly divisible triangular number
# Problem 12 
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

# num = 28
require 'Prime'
# (1..num).select { |n|num % n == 0}
fact_count = 0
i = 12350
tri_nums = (0..i).to_a.inject(&:+)
while fact_count <= 500
  i += 1
  p tri_nums = tri_nums + i
  triangle_num = tri_nums
  fact_count = (1..triangle_num).select { |n|triangle_num % n == 0}.count
end
p fact_count
# p (0..12350).to_a.inject(&:+)

# p Prime.prime_division(76576500)